### ISSUE TITLE
Use PAT to push on main

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/massa-localized-docs#5]
Soon, the `main` branch will be protected. So we won't be able to push on it without a `PAT`. We need to rewrite some parts of the Github Workflow to use the `PAT` to push on the `main` branch.

**Comment by SlnPons** [comment]
@thomas-senechal do I have to test this ticket or Adrien did it?

**Comment by thomas-senechal** [comment]
> @thomas-senechal do I have to test this ticket or Adrien did it?

Adrien did it. Everything is working well.
